version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:5314cd80-f0cb-434b-ba8e-899d645ef79d@git.heroku.com/heroku-automation-app