version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - run:
          command: |
            echo "This is first step"

      - run:
          command: echo "This is second step"
          when: always

      - run:
          command: |
            echo "This is first step"

      - run:
          command: echo "This is second step"
          when: always