version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest

    phpunit:
      - run:
          command: phpunit testphpunit.php
    steps:
      - checkout
      - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
          - "ssh-rsa xxxxxxx ishiinaoki@mac-book-air.local"
      - deploy:
          name: heroku deploy
          command: |
                  git push https://heroku:5314cd80-f0cb-434b-ba8e-899d645ef79d@git.heroku.com/heroku-automation-app.git master