version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: bash .circleci/setup-heroku.sh
      - deploy:
          name: heroku deploy
          command: |
            git push https://git.heroku.com/heroku-automation-app.git master
